// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dirwsxgkmwiaeadmlrtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcndzeGdrbXdpYWVhZG1scnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDEyMTcsImV4cCI6MjA2NDUxNzIxN30.5pHOu856lOU1FCvjmy1fMA_la1MP-epULOjfMzbnBtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);